name: Backend CI/CD
on:
  workflow_call:
    secrets:
      packages_token:
        required: true

jobs:
  build:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: strairecloud-api
          password: ${{ secrets.packages_token }}

      - name: Get docker tag
        id: get_tag
        uses: strairecloud/SharedCI@master
        with:
          func: get_image_tag
          packages_token: ${{ secrets.packages_token }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          tags: ${{ steps.get_tag.outputs.image_tag_latest }},${{ steps.get_tag.outputs.image_tag_versioned }}
          build-args: |
            NODE_ENV=production
            GIT_COMMIT=${{ github.sha }}
            ${{ github.repository == 'strairecloud/WebClient' && 'WEBCLIENT_API_URL=https://api.strairecloud.com' }}
          secrets: |
            github_packages_token=${{ secrets.packages_token }}

      - name: Update chart
        if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
        uses: strairecloud/SharedCI@master
        with:
          func: dispatch_chart_update
          packages_token: ${{ secrets.packages_token }}
